# Generated by Django 5.2.10 on 2026-01-24 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('studio', models.CharField(max_length=50)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('playtime_minutes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('steam_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('join_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_nickname', models.CharField(max_length=30)),
                ('match_score', models.IntegerField(default=0)),
                ('top_games', models.ManyToManyField(blank=True, to='steam_match.game')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='steam_match.gamer')),
            ],
        ),
    ]
