# Generated by Django 5.2.10 on 2026-01-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_match', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='steam_nickname',
            new_name='steam_username',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='steam_id',
        ),
        migrations.AddField(
            model_name='gamer',
            name='steam_username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
