# Generated by Django 5.2.10 on 2026-01-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_course_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='student',
            name='cell_phone_number',
            field=models.CharField(default='86 99999-9999', max_length=13),
            preserve_default=False,
        ),
    ]
